attributes: []
characters: []
commands: []
commentDelimiters:
  inlineDelimiter: '#'
comments:
- beginString: ;.*
  regularExpression: true
completions: []
extensions: []
filenames:
- keyString: .gitconfig
- keyString: .gitmodules
- keyString: gitconfig
interpreters: []
keywords:
- beginString: ^[\t ]*\w+[\t ]*(?<=)
  regularExpression: true
kind: code
metadata:
  author: 1024jp
  distributionURL: https://coteditor.com
  lastModified: '2023-05-05'
  license: Same as CotEditor
  version: 1.1.0
numbers:
- beginString: (?<!\w)[0-9.][0-9.]*(e-?[0-9.]+)?\b
  regularExpression: true
outlineMenu:
- beginString: ^\[(.+)\]
  bold: true
  description: section
  keyString: $1
strings:
- beginString: '"'
  endString: '"'
- beginString: ''''
  endString: ''''
types:
- beginString: ^\[
  endString: \]
  regularExpression: true
values:
- beginString: 'false'
- beginString: 'true'
variables: []
